# logfilename                                          [owner:group]      mode count size   when  flags
/tmp/kimbir.export-and-deploy-kbi-work-calendar.out    kimbirkelund:wheel 644  3     1024   *     N
/tmp/kimbir.export-and-deploy-kbi-work-calendar.err    kimbirkelund:wheel 644  3     1024   *     N
